<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9468" started-at="2018-09-25T06:06:11Z" finished-at="2018-09-25T06:06:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9468" started-at="2018-09-25T06:06:11Z" finished-at="2018-09-25T06:06:20Z">
      <class name="com.qa.testcases.SampleTestCase">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="setup" is-config="true" duration-ms="5743" started-at="2018-09-25T11:36:11Z" finished-at="2018-09-25T11:36:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="launch()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="launch" duration-ms="18" started-at="2018-09-25T11:36:17Z" finished-at="2018-09-25T11:36:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="reportteardown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="reportteardown" is-config="true" duration-ms="8" started-at="2018-09-25T11:36:17Z" finished-at="2018-09-25T11:36:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=launch status=SUCCESS method=SampleTestCase.launch()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportteardown -->
        <test-method status="FAIL" signature="title()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="title" duration-ms="15" started-at="2018-09-25T11:36:17Z" finished-at="2018-09-25T11:36:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title dows not match expected [Google@123] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title dows not match expected [Google@123] but found [Google]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.qa.testcases.SampleTestCase.title(SampleTestCase.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title -->
        <test-method status="PASS" signature="reportteardown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="reportteardown" is-config="true" duration-ms="408" started-at="2018-09-25T11:36:17Z" finished-at="2018-09-25T11:36:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=title status=FAILURE method=SampleTestCase.title()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportteardown -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.testcases.SampleTestCase@57fffcd7]" name="teardown" is-config="true" duration-ms="3243" started-at="2018-09-25T11:36:17Z" finished-at="2018-09-25T11:36:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.testcases.SampleTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
